"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

references:
www.marinamele.com/from-a-python-script-to-a-portable-mac-application-with-py2app
www.rkblog.rk.edu.pl/w/p/building-mac-os-x-applications-py2app/
"""

from setuptools import setup

APP = ['anaqa.py']
DATA_FILES = ["anaqa_logo_and_name.png", "anaqa_logo.png", "ARIALN.TTF"]
OPTIONS = {'argv_emulation': True,
           'iconfile': 'anaqa_logo.icns',
           'packages': ['reportlab'],
           'includes': ['PyQt4', 'PyQt4.QtCore', 'PyQt4.QtGui'],
	   'excludes': ['PyQt4.QtDesigner', 'PyQt4.QtNetwork',
                        'PyQt4.QtOpenGL', 'PyQt4.QtScript', 'PyQt4.QtSql',
                        'PyQt4.QtTest', 'PyQt4.QtWebKit', 'PyQt4.QtXml',
                        'PyQt4.phonon']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
